### ISSUE TITLE
Suggestion to Lesson "NUMBER TO STRING"

### ISSUE THREAD

**Issue by Sequoia** [sethvincent/javascripting#63]
*migrated from https://github.com/nodeschool/discussions/issues/760
/cc @closer76 @SomeoneWeird @a0viedo @martinheidegger*
1. The example of this lesson is shown as:
   ```
   var n = 256;
   n.toString();
   ```
   And it might lead to confusion, since ```.toString()``` won't modify ```n``` itself and this statement doesn't make much sense. Suggested to be:
   ```
   var n = 256;
   n = n.toString();
   ```

2. I tried the following code snippet for the chanllenge:
   ```
   var n = 128;
   n.toString();
   console.log(n);   // well, n is still a number, not a string
   ```
   and it passed the verification (which is wrong). I think the problem is the verification script checks the output only, and in this case, the output will always be ```128``` no matter ```n``` is a number or a string.

   I suggest to ask challengers to print out "the length of the string". If the challenger tries to use ```.length``` on a number, he or she will get "undefined".

**Comment by sethvincent** [comment]
Made that update recently: https://github.com/sethvincent/javascripting/commit/f96dfd1d0b1324c054e430e27ae2e1ca7dc628b7

So it should be in the latest version.

**Comment by viciousmelicious** [comment]
Hi,
var n = 128;
n.toString();
console.log(n);

I tried the above code snippet as well, but this is what the terminal says to me: 

{ [Error: Command failed: /bin/sh -c node "/Users/viciousmelicious/number-to-string.js"
module.js:338
    throw err;
          ^
Error: Cannot find module '/Users/viciousmelicious/number-to-string.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c node "/Users/viciousmelicious/number-to-string.js"' }
Melissas-MacBook-Pro:~ viciousmelicious$

Not sure why I am getting this. I was supposed to create this file within the variables folder so the path would be users/viciousmelicious/javascripting/variables/number-to-string.js like the previous exercises correct? I am definitely a beginner and finally feel like I fond a tutorial that takes it step by step in a way that I am ACTUALLY learning, so would liek to know how I get to the correct directory in the terminal if that is my only issue...thanks!

**Comment by sethvincent** [comment]
@viciousmelicious hey, thanks for the nice feedback! It's awesome to hear that this tutorial is helping.

That error is saying that the number-to-string.js file is not in the directory you're in.

You can run the `pwd` command and that will show you the full path of the directory you're in.

Or run the `ls` to see which files are in your current directory.

I probably wouldn't make a variables folder, but just have all the files for each lesson in one folder.

About the code snippet: make sure to set `n = n.toString()` so that `n` is updated to the string value.

**Comment by SomeoneWeird** [comment]
What we can probably do to fix the original issue is load the file content up in a vm and check that the variables actually match what we're expecting too.

**Comment by viciousmelicious** [comment]
Hi all,

Thanks so much!

I actually ended up changing my code to this:
var n = 128;console.log(n.toString());
This is the way that was suggested on W3 and it makes sense to call the
number from the var n in the console.

In the next exercise, it seems to be calling the number 128 at the end of
my if/else statement. Is there any reason this could be happening?

My code on the if-statement.js exercise:

var fruit = "orange";
if (fruit.length > 5) {
  console.log('The fruit name has more than five characters.');
}
else {
  console.log('The fruit name has five characters or less.');
}

and in the terminal i get this:

Melissas-MacBook-Pro:~ viciousmelicious$ javascripting verify
javascripting/variables/if-statement.js

-------------------

# *O-oh, something isn't working.*


# *But don't panic!*


-------------------

## *Check your solution:*


Solution

===================


128



Your Attempt

===================


The fruit name has more than five characters.



Difference

===================


The fruit name has more than five characters.128



## *Additional troubleshooting:*


- Did you type the name of the file correctly? You can check by running ls
javascripting/variables/if-statement.js, if you see ls: cannot access
javascripting/variables/if-statement.js: No such file or directory then you
should create new file / rename existing or change directories to the one
with file

- Make sure you didn't omit parens, since otherwise compiler would not be
able to parse it

- Make sure you didn't do any typos in the string itself


It's like the two exercises are merging somehow (if that makes sense!)

Thanks again for your help :)

Melissa

**Comment by gabojkz** [comment]
Hi this is mi code in the if statement exercise 
var fruit= 'orange';
if(fruit.length>5){
	console.log('The fruit name has more than five characters.');
}else{
	console.log('The fruit name has more than five characters.');
}
console.log(fruit);

it work but and the the appears orange and I don't know how to remove it.
