### ISSUE TITLE
troubleshooting.md translations

### ISSUE THREAD

**Issue by sethvincent** [sethvincent/javascripting#84]
We should create `troubleshooting_ko.md` and `troubleshooting_es.md` files before doing the next npm release.

Currently I get this error when the `verify` command fails and I have a language selected that doesn't have a troubleshooting_xx.md file:

```
Error: ENOENT, no such file or directory '/Users/sethvincent/workspace/javascript-modules/nodeschool/javascripting/troubleshooting_es.md'
```

**Comment by esalinas00** [comment]
I'll update some of the spanish translations and I'll include the troublesthooting_es with the pull request when I finish.

**Comment by a0viedo** [comment]
see https://github.com/sethvincent/javascripting/pull/94

**Comment by esalinas00** [comment]
#93 I added a troubleshooting_es in that pull request too :S
Also made some modifications to the existing spanish translations (the code examples are now in english) so the command 'javascript verify' would work on it.

**Comment by a0viedo** [comment]
@esalinas00 I didn't knew about that PR, my bad. Two things, could you separe that in two PRs? One for troubleshooting_es.md and another one for the code examples corrections. Good catch, but we need just to keep the same string literals, not necessarily the name of the variables (i.e. verify would work with `var ejemplo = "some string"; console.log(ejemplo)` too).

**Comment by esalinas00** [comment]
@a0viedo I decided to change the variable names because in the other language translations the variable names are in english. I though it was a convention, but maybe they are in english because the other languages available use special characters. I'll change the variables' names back to spanish if you think that would be better.

I have no problem leaving your troubleshooting_es.md, it will mean less merges.

**Comment by a0viedo** [comment]
@esalinas00 maybe we could make the best from both :)

**Comment by esalinas00** [comment]
@a0viedo cool, I commented on your pull request.
